default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://github.com/zinok/precommit-pylint
    rev: v0.6.0
    hooks:
      - id: precommit-pylint
        args:
          - --limit=10.0
          - --output
